# Generated by Django 4.2.7 on 2025-10-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('countries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='population',
            field=models.BigIntegerField(default=0),
        ),
    ]
